import { Store, State, Selector, Select } from '@ngxs/store';
import { Project } from './project';
import { Observable } from 'rxjs';

export class ProjectStateModel {
  readonly projects: Project[];
}

@State<ProjectStateModel>({
  name: 'projects',
  defaults: {
    projects: [
      { name: 'Autogenerated folders', owner: 'Bob Tirva', size: 4 },
      { name: 'Junk emails', owner: 'Simon Dasherd', size: 32 }
    ]
  }
})

export class ProjectsState {
  @Selector()
  static getProjects(state: ProjectStateModel) {
    return state.projects;
  }
}

