import { Project } from './project';

export const Projects: Array<Project> = [
    { name: 'Autogenerated folders', owner: 'Bob Tirva', size: 4 },
    { name: 'Junk emails', owner: 'Simon Dasherd', size: 32 }
];
