import { Injectable } from '@angular/core';
import { Store } from '@ngxs/store';
import { Project } from './project';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ProjectsService {
  private Projects: Array<Project>;

  constructor(private store: Store) {
    this.Projects = [
      { name: 'Autogenerated folders', owner: 'Bob Tirva', size: 4 },
      { name: 'Junk emails', owner: 'Simon Dasherd', size: 32 }
    ];
    this.store.dispatch(this.Projects);
  }

  getProjects(): Observable<Project[]> {
    return this.store.select<Project[]>(state => state);
  }
}
